### ISSUE TITLE
Remove duplicate text

### ISSUE THREAD

**Issue by ppminkov** [isovector/reasonablypolymorphic.com#11]
Hi Sandy,
I tried to create a branch with the correction and do a Pull request, but it fails with:
Permission to isovector/reasonablypolymorphic.com.git denied to ppminkov.
But it doesn't matter. 

Just remove this text from chapter 'More Types': "I tell you this not to belittle them, but to inspire you. It’s not a particularly difficult topic, and if you can manage to hold on just a little longer, you’ll have the tools under your belt in order to compete with the best of them"

The book is beautiful, I really enjoyed it. Keep walking!

Best Regards,
Petko

**Comment by isovector** [comment]
Thanks! I've updated the source material with the fix. Unfortunately the build pipeline is no longer up and running, so it won't show up on the website. I plan to remaster HTTW into a fully-fledged book after I'm finished with my [current one,](https://www.patreon.com/designandinterpretation) so this fix will make it into production at some point!

**Comment by isovector** [comment]
Fixed in 17e817be693ab3ecf17fd2093d39ebbbbdddbb29

**Comment by ppminkov** [comment]
Glad to help, the book is really good.
Best, 
Petko
