### ISSUE TITLE
Use utteranc.es for comments

### ISSUE THREAD

**Issue by TheMatten** [isovector/reasonablypolymorphic.com#12]
Compared to https://utteranc.es, which uses GitHub issues for comments, is dumb simple and looks nice, Disqus has few ["features"](https://fatfrogmedia.com/delete-disqus-comments-wordpress/) that may not be that user friendly. And after all, I guess more people reading your blog have GitHub account than Disqus one :wink:

TL;DR: Disqus bad, Utteranc.es good

**Comment by isovector** [comment]
done. thanks!
