### ISSUE TITLE
Tag links broken

### ISSUE THREAD

**Issue by josephcsible** [isovector/reasonablypolymorphic.com#13]
At the top-right of each blog post is a list of tags that it's in. When I click any of these tag links (e.g., https://reasonablypolymorphic.com/tags/haskell.html), instead of being taken to a list of other posts with the same tag, I end up on a 404 page.

**Comment by isovector** [comment]
Thanks! Turns out my global gitignore was preventing them from being pushed. Should be fixed within a few minutes.
