### ISSUE TITLE
Link to self for tags goes absolute

### ISSUE THREAD

**Issue by philderbeast** [isovector/reasonablypolymorphic.com#5]
The link to self for tags goes absolute.

Reproduction steps:

1. Navigate to http://reasonablypolymorphic.com/tags/neptune.html
2. Click the link [Posts tagged "neptune"]
3. Navigating to http://tags/neptune.html fails.

From `templates/tags.html` ...

```html
<header>
    <h1><a href="$url$">$title$</a></h1>
</header>
```

**Comment by isovector** [comment]
thanks for noticing this!
